name: material_yes_no_buttons_example
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'
dependencies:
  angular: 5.0.0-alpha+13
  angular_components: 0.9.0-alpha+13
  angular_gallery_section:
    path: ../../angular_gallery_section
  build_config: ^0.2.6
