name: angular_gallery_section
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.0.0-dev.64.2 <3.0.0'
dependencies:
  analyzer: ^0.32.0
  angular: ^5.0.0-beta+1
  angular_components: 0.9.0-beta+1
  build: '>=0.11.1 <0.13.0'
  build_config: '>=0.2.6 <0.4.0'
  glob: ^1.1.5
  markdown: ^1.1.1
  mustache: ^1.0.0
  path: ^1.6.1
