name: angular_gallery_section
version: 0.0.1-dev
description:
homepage:
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.0.0-dev.32.0 <2.0.0'
dependencies:
  analyzer: ^0.31.1
  angular: 5.0.0-alpha+9
  angular_components: 0.9.0-alpha+9
  build: '>=0.11.1 <0.13.0'
  build_config: ^0.2.5
  glob: ^1.1.5
  markdown: ^1.1.1
  mustache: ^1.0.0
  path: ^1.5.1
