name: angular_components_example
description: An example app using the angular_components package.
environment:
  sdk: '>=1.24.0 <2.0.0'
dependencies:
  angular: 5.0.0-alpha
  angular_components: 0.9.0-alpha
  angular_forms: 1.0.1-alpha
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  sass_builder: ^1.0.0
dev_dependencies:
  webdriver: ^1.2.1
transformers:
- sass_builder
- angular:
    entry_points: web/main.dart
- $dart2js:
    commandLineOptions: [--trust-type-annotations, --trust-primitives, --show-package-warnings, --dump-info]
- dart_to_js_script_rewriter
