name: angular_components_example
description: An example app using the angular_components package.
environment:
  sdk: '>=1.24.0 <2.0.0'
dependencies:
  angular: ^4.0.0
  angular_components: ^0.7.1
  angular_forms: ^1.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
dependency_overrides:
  angular_components:
    git:
      url: https://github.com/dart-lang/angular_components
      ref: add-auto-suggest
dev_dependencies:
  webdriver: ^1.2.1
transformers:
- angular:
    entry_points: web/main.dart
- $dart2js:
    commandLineOptions: [--trust-type-annotations, --trust-primitives, --show-package-warnings, --dump-info]
- dart_to_js_script_rewriter
