name: angular_components_example
description: An example app using the angular_components package.
environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'
dependencies:
  angular: 5.0.0-alpha+5
  angular_components: 0.9.0-alpha+4
  angular_forms: 1.0.1-alpha+5
  browser: ^0.10.0
dev_dependencies:
  webdriver: ^1.2.1
  build_runner: ^0.7.0
  build_web_compilers: ^0.2.0
  sass_builder: ^1.1.2
dependency_overrides:
  angular_components:
    git:
      url: https://github.com/dart-lang/angular_components.git
      ref: github-sync
