name: angular2_components_example
description: An example app using the angular_components package.
version: 1.2.0
environment:
  sdk: '>=1.20.0 <2.0.0'
dependencies:
  angular2: any
  angular2_components: ^0.4.1-alpha
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
dev_dependencies:
  webdriver: ^1.2.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#CORE_DIRECTIVES'
    - 'package:angular2/common.dart#FORM_DIRECTIVES'
    entry_points: web/main.dart
- $dart2js:
    commandLineOptions: [--trust-type-annotations, --trust-primitives, --show-package-warnings, --dump-info]
- dart_to_js_script_rewriter
