name: material_datepicker_example
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.0.0-dev.46.0 <2.0.0'
dependencies:
  angular: 5.0.0-alpha+12
  angular_components: 0.9.0-alpha+12
  angular_gallery_section:
    path: ../../angular_gallery_section
  build_config: ^0.2.6
  quiver: '>=0.24.0 <0.30.0'
