name: material_toggle_example
version: 0.0.1-dev
description:
homepage:
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.0.0-dev.28.0 <2.0.0'
dependencies:
  angular: 5.0.0-alpha+8
  angular_components: 0.9.0-alpha+8
  angular_gallery_section:
    path: ../../angular_gallery_section
  build_config: ^0.2.5
