name: angular_gallery
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.0.0-dev.56.0 <2.0.0'
dependencies:
  angular: 5.0.0-alpha+14
  angular_components: 0.9.0-alpha+14
  angular_forms: 2.0.0-alpha+6
  angular_router: 2.0.0-alpha+13
  build: '>=0.11.1 <0.13.0'
  build_config: ^0.2.6
  mustache: ^1.0.0
