name: material_progress_example
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.0.0-dev.56.0 <2.0.0'
dependencies:
  angular: 5.0.0-alpha+14
  angular_components: 0.9.0-alpha+14
  angular_gallery_section:
    path: ../../angular_gallery_section
  build_config: ^0.2.6
