name: material_slider_example
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.0.0-dev.60.0 <2.0.0'
dependencies:
  angular: 5.0.0-alpha+15
  angular_components: 0.9.0-alpha+15
  angular_gallery_section:
    path: ../../angular_gallery_section
  build_config: '>=0.2.6 <0.4.0'
