targets:
  $default:
    builders:
      angular|angular:
        enabled: True
      angular_gallery|angular_gallery:
        options:
          styleUrls: ["gallery.scss.css"]
          galleryTitle: "AngularDart Gallery"
          examples: "app_layout_example,material_button_example,material_checkbox_example,material_chips_example,material_datepicker_example,material_dialog_example,material_expansionpanel_example,material_icon_example,material_input_example,material_list_example,material_menu_example,material_popup_example,material_progress_example,material_radio_example,material_select_example,material_slider_example,material_spinner_example,material_stepper_example,material_tab_example,material_toggle_example,material_tooltip_example,material_tree_example,material_yes_no_buttons_example,scorecard_example"
      angular_components|scss_builder:
        enabled: True
      angular_gallery_section:
        enabled: False
      build_web_compilers|dart2js_archive_extractor:
        options:
          filter_outputs: false
      build_web_compilers|entrypoint:
        generate_for:
        - web/main.dart
        options:
          dart2js_args:
          - --fast-startup
          - --minify
          - --trust-type-annotations
          - --trust-primitives
          - --dump-info
          - --preview-dart-2
