name: material_input_example
version: 0.0.1-dev
description:
homepage:
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'
dependencies:
  angular: 5.0.0-alpha+7
  angular_components: 0.9.0-alpha+7
  angular_forms: 1.0.1-alpha+7
  angular_gallery_section:
    path: ../../angular_gallery_section
  build_config: ^0.2.4
