name: material_input_example
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.0.0-dev.64.2 <3.0.0'
dependencies:
  angular: ^5.0.0-beta+2
  angular_components: 0.9.0-beta+2
  angular_forms: ^2.0.0-beta+2
  angular_gallery_section:
    path: ../../angular_gallery_section
  intl: '>=0.14.0 <0.16.0'
  build_config: '>=0.2.6 <0.4.0'
